using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using Microsoft.AspNetCore.Authorization;
using WebApplication1.Data;  
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Controllers;


public class HomeController : Controller
{
    private readonly HttpClient _httpClient;
    private readonly ApplicationDbContext _context;  
    private readonly ListingProjects _listingProjects;
    
    public HomeController(HttpClient httpClient, ApplicationDbContext context)
    {
        _httpClient = httpClient; 
        _context = context;
    }

    [Authorize]
    public IActionResult Index()
    {
        var portalUserModelRef = _context.UsersDBTable
            .Select(u => new WebApplication1.Models.PortalUsers
            {
                Name = u.Name,
                Age = u.Age,
                Location = u.Location
            }).ToList();

        return View(portalUserModelRef);
    }

    public IActionResult Edit(int? Id)
    {
        if (Id == null)
        {
            return NotFound("The provided Id is null.");
        }

        var editedUserModelRef = _context.ListingDTO_DBTable
            .Include(dto => dto.ListingProjectsFK) // Include related data
            .FirstOrDefault(e => e.ListingProjectsFKId == Id);

        if (editedUserModelRef == null)
        {
            return NotFound($"No entry found for Id = {Id}");
        }

        return View(editedUserModelRef);
    }



    [HttpPost]
    public IActionResult Update(ListingProjectsDTO updatedUserModelRef)
    {
        if (updatedUserModelRef == null || updatedUserModelRef.ListingProjectsFKId == null)
        {
            // Return JSON error response for AJAX or standard NotFound for non-AJAX
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return Json(new { success = false, message = "Invalid data received." });
            }
            return NotFound(); 
        }

        var oldListingProjects = _context.ListingDTO_DBTable.FirstOrDefault(e => e.ListingProjectsFKId == updatedUserModelRef.ListingProjectsFKId);
        if (oldListingProjects == null)
        {
            // Return JSON error response for AJAX or standard NotFound for non-AJAX
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return Json(new { success = false, message = "Record not found." });
            }
            return NotFound(); 
        }

        try
        {
            // Update the record
            _context.Entry(oldListingProjects).CurrentValues.SetValues(updatedUserModelRef);
            _context.SaveChanges();

            // If AJAX request, return JSON success
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return Json(new { success = true, message = "Record updated successfully!" });
            }

            // Otherwise, redirect to the dashboard
            return RedirectToAction("TestDashboard1");
        }
        catch (Exception ex)
        {
            // Handle errors and provide feedback for AJAX or non-AJAX
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return Json(new { success = false, message = $"An error occurred: {ex.Message}" });
            }

            // For non-AJAX requests, consider logging and returning a friendly error page
            return StatusCode(500, "An error occurred while updating the record.");
        }
    }


   
   [HttpGet]
   public IActionResult InsertListings()
   {
       // Create a list with a single new ListingProjectsDTO to initialize the form
       var listings = new List<ListingProjectsDTO>
       {
           new ListingProjectsDTO() // Add an empty DTO for user input
       };

       // Pass the list to the view
       return View(listings);
   }

   [HttpPost]
   [ValidateAntiForgeryToken]
   public async Task<IActionResult> InsertListings(List<ListingProjectsDTO> listingProjectsDtos)
   {
       if (ModelState.IsValid)
       {
           try
           {
               
               foreach (var dto in listingProjectsDtos)
               {
                   // Add ListingProjects entry to the context
                   var addListings = new ListingProjects
                   {
                       Id = dto.ListingId,
                       ListingName = dto.ListingName_DTO
                   };
                   _context.ListingDBTable.Add(addListings);

                   // Add the corresponding DTO (Id will be generated by EF when changes are saved)
                   var addDTO = new ListingProjectsDTO
                   {
                       ListingProjectsFKId = addListings.Id, // EF Core handles Id assignment during SaveChanges
                       ListingName_DTO = dto.ListingName_DTO
                   };
                   _context.ListingDTO_DBTable.Add(addDTO);
               }

// Save all changes in one batch
               await _context.SaveChangesAsync();

// Refresh and pass the updated listings
               var listings = await _context.ListingDBTable
                   .Select(listing => new ListingProjectsDTO
                   {
                       ListingId = listing.Id,
                       ListingName_DTO = listing.ListingName
                   })
                   .ToListAsync();

               return RedirectToAction("TestDashboard1");


               //return View("TestDashboard1", listings);
           }
           catch (DbUpdateException ex)
           {
               ModelState.AddModelError("", "An error occurred while saving the listing.");
           }
       }

       return View(listingProjectsDtos);
   }



    public IActionResult Privacy()
    {
        return View();
    }
   
    
    public async Task<IActionResult> DeleteDetails(int? id, bool? saveChangesError = false)
    {
        if (id == null)
        {
            return NotFound();
        }

        var listingToBeDeleted = await _context.ListingDBTable
            .AsNoTracking()
            .FirstOrDefaultAsync(m => m.Id == id);
        if (listingToBeDeleted == null)
        {
            return NotFound();
        }

        if (saveChangesError.GetValueOrDefault())
        {
            ViewData["ErrorMessage"] =
                "Delete failed. Try again, and if the problem persists " +
                "see your system administrator.";
        }
        ViewData["OKMessage"] =
            "confirm deletion";

        return View(listingToBeDeleted);
    }
    
    [HttpPost, ActionName("DeleteDetails")]
    [ValidateAntiForgeryToken]
    [HttpPost]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        try
        {
            // Find the listing to be deleted
            var listingToBeDeleted = await _context.ListingDBTable.FindAsync(id);
            if (listingToBeDeleted == null)
            {
                return Json("Not found at all");
            }

            // Delete related entries from ListingDTO_DBTable
            var relatedEntries = await _context.ListingDTO_DBTable
                .Where(dto => dto.ListingProjectsFKId == id) // Compare with the foreign key ID
                .ToListAsync();
            _context.ListingDTO_DBTable.RemoveRange(relatedEntries);

            // Now delete the listing
            _context.ListingDBTable.Remove(listingToBeDeleted);
            await _context.SaveChangesAsync();

            return Json("success!");
        }
        catch (Exception ex)
        {
            return Json("An error occurred: " + ex.Message);
        }
    }
    
    
    
    [AllowAnonymous]

    public async Task<IActionResult> TestDashboard1()
    {
        var datasource = _context.ListingDBTable.AsQueryable();
        var query = datasource
            .Select(x => new ListingProjectsDTO {
                ListingId = x.Id,
                ListingName_DTO = x.ListingName,
            });
        var listings = await query.ToListAsync();

        return View(listings);
    }
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
 
}